/**
 * generated by Xtext 2.24.0
 */
package ishikawa.tests;

import ishikawa.tests.IshikawaInjectorProvider;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

/* @ExtendWith(/* name is null */)
@InjectWith(IshikawaInjectorProvider.class) */@SuppressWarnings("all")
public class IshikawaParsingTest {
  /* @Inject
   */private /* ParseHelper<Effect> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field IshikawaParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved"
      + "\njoin cannot be resolved");
  }
}
