/*
 * generated by Xtext 2.24.0
 */
package ishikawa;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class IshikawaStandaloneSetup extends IshikawaStandaloneSetupGenerated {

	public static void doSetup() {
		new IshikawaStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
