/*
 * generated by Xtext 2.24.0
 */
package ishikawa.ui.quickfix;

import org.eclipse.jface.text.BadLocationException;
import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;

import ishikawa.validation.IshikawaValidator;

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class IshikawaQuickfixProvider extends DefaultQuickfixProvider {

	@Fix(IshikawaValidator.INVALID_EFFECT_NAME)
	@Fix(IshikawaValidator.NULL_EFFECT_NAME)
	public void invalidOrNullEffectName(final Issue issue, IssueResolutionAcceptor acceptor) {
		acceptor.accept(issue, "Set default name", "Set a default name for this effect.", "upcase.png", new IModification() {
			public void apply(IModificationContext context) throws BadLocationException {
				IXtextDocument xtextDocument = context.getXtextDocument();
				xtextDocument.replace(issue.getOffset(), issue.getLength(), "\"EffectExampleName\"");
			}
		});
	}
	
	@Fix(IshikawaValidator.INVALID_CATEGORY_NAME)
	public void invalidOrNullCategoryName(final Issue issue, IssueResolutionAcceptor acceptor) {
		acceptor.accept(issue, "Set default name", "Set a default name for this category.", "upcase.png", new IModification() {
			public void apply(IModificationContext context) throws BadLocationException {
				IXtextDocument xtextDocument = context.getXtextDocument();
				xtextDocument.replace(issue.getOffset(), issue.getLength(), "\"CategoryExampleName\"");
			}
		});
	}
	
	@Fix(IshikawaValidator.INVALID_CAUSE_NAME)
	public void invalidOrNullCauseName(final Issue issue, IssueResolutionAcceptor acceptor) {
		acceptor.accept(issue, "Set default name", "Set a default name for this cause.", "upcase.png", new IModification() {
			public void apply(IModificationContext context) throws BadLocationException {
				IXtextDocument xtextDocument = context.getXtextDocument();
				xtextDocument.replace(issue.getOffset(), issue.getLength(), "\"CauseExampleName\"");
			}
		});
	}

}
