/**
 *
 * $Id$
 */
package ishikawa_model.validation;

import ishikawa_model.Cause;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ishikawa_model.Category}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CategoryValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateDescription(String value);
	boolean validateCauses(EList<Cause> value);
}
