/*
 * generated by Xtext 2.24.0
 */
package ishikawa.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class IshikawaUiModule extends AbstractIshikawaUiModule {

	public IshikawaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
