/**
 *
 * $Id$
 */
package dataoriented_ishikawa_model.validation;

import dataoriented_ishikawa_model.AttributeFilter;
import dataoriented_ishikawa_model.IncludedReference;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link dataoriented_ishikawa_model.DataFeeder}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DataFeederValidator {
	boolean validate();

	boolean validateDomainElementSelector(String value);
	boolean validateIncludedReference(EList<IncludedReference> value);
	boolean validateAttributefilter(AttributeFilter value);

	boolean validateName(String value);
}
