/**
 *
 * $Id$
 */
package dataoriented_ishikawa_model.validation;

import dataoriented_ishikawa_model.Category;
import dataoriented_ishikawa_model.DataFeeder;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link dataoriented_ishikawa_model.Effect}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EffectValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateCategories(EList<Category> value);
	boolean validateDataFeeder(DataFeeder value);
}
