/*
 * generated by Xtext 2.24.0
 */
package ishikawa.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractIshikawaScopeProvider extends DelegatingScopeProvider {
}
