/*
 * generated by Xtext 2.24.0
 */
package ishikawa.parser.antlr;

import com.google.inject.Inject;
import ishikawa.parser.antlr.internal.InternalIshikawaParser;
import ishikawa.services.IshikawaGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class IshikawaParser extends AbstractAntlrParser {

	@Inject
	private IshikawaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalIshikawaParser createParser(XtextTokenStream stream) {
		return new InternalIshikawaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Effect";
	}

	public IshikawaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IshikawaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
