/*
 * generated by Xtext 2.24.0
 */
package ishikawa.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class IshikawaAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("ishikawa/parser/antlr/internal/InternalIshikawa.tokens");
	}
}
