<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dataoriented_ishikawa_model" nsURI="http://dataoriented_ishikawa_model"
    nsPrefix="dataoriented_ishikawa_model">
  <eClassifiers xsi:type="ecore:EClass" name="Effect">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" lowerBound="1"
        upperBound="-1" eType="#//Category" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataFeeder" lowerBound="1"
        eType="#//DataFeeder" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="causes" lowerBound="1"
        upperBound="-1" eType="#//Cause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cause" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="realizes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompoundCause" eSuperTypes="#//Cause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subCauses" lowerBound="1"
        upperBound="-1" eType="#//Cause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataLinkedCause" eSuperTypes="#//Cause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataFeeder" lowerBound="1"
        eType="#//DataFeeder" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotMappedCause" eSuperTypes="#//Cause"/>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeFilter"/>
  <eClassifiers xsi:type="ecore:EClass" name="IncludedReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="DOF">
    <eStructuralFeatures xsi:type="ecore:EReference" name="effect" lowerBound="1"
        eType="#//Effect" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataFeeder">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domainElementSelector"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includedReference" upperBound="-1"
        eType="#//IncludedReference" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributefilter" eType="#//AttributeFilter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
