/*
 * generated by Xtext 2.24.0
 */
package ishikawa.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import ishikawa.IshikawaRuntimeModule;
import ishikawa.IshikawaStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class IshikawaIdeSetup extends IshikawaStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new IshikawaRuntimeModule(), new IshikawaIdeModule()));
	}
	
}
