/*
 * generated by Xtext 2.24.0
 */
package ishikawa.ui.tests;

import com.google.inject.Injector;
import ishikawa.xtex.ui.internal.XtexActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class IshikawaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtexActivator.getInstance().getInjector("ishikawa.Ishikawa");
	}

}
