/*
 * generated by Xtext 2.24.0
 */
package ishikawa.ui;

import com.google.inject.Injector;
import ishikawa.xtex.ui.internal.XtexActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IshikawaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(XtexActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		XtexActivator activator = XtexActivator.getInstance();
		return activator != null ? activator.getInjector(XtexActivator.ISHIKAWA_ISHIKAWA) : null;
	}

}
